version: 2.1

workflows:
  ci:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test